version: '3.8'

services:
  app:
    container_name: mainstack_product_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # - PORT=3009
      # - DB_TYPE = postgres
      # - DB_HOST=database
      # - DB_PORT=5432
      # - DB_USER=${DB_USERNAME}
      # - DB_PASS=${DB_PASSWORD}
      # - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      # - database
      - redis
    networks:
      - mainstack_product_api_network

  redis:
    container_name: mainstack_product_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - mainstack_product_api_network

  # database:
  #   container_name: air_quality_postgres
  #   image: postgres:13
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - air_quality_network

volumes:
  redis:
    driver: local
  # postgres-data:
  #   driver: local

networks:
  mainstack_product_api_network:
