version: '3.8'

services:
  app:
    container_name: mainstack_product_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
      - mongo
    networks:
      - mainstack_product_api_network

  redis:
    container_name: mainstack_product_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - mainstack_product_api_network

  mongo:
    container_name: mainstack_product_mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mainstack_product_api_network

volumes:
  redis:
    driver: local
  mongo-data:
    driver: local

networks:
  mainstack_product_api_network:
